Prerelease version number bumped.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1,6 +1,6 @@
 #! /bin/sh
 # Guess values for system-dependent variables and create Makefiles.
-# Generated by Autoconf 2.52 for cdsware 0.01-pre3.
+# Generated by Autoconf 2.52 for cdsware 0.01-pre4.
 #
 # Report bugs to <cds.support@cern.ch>.
 #
@@ -147,8 +147,8 @@ mandir='${prefix}/man'
 # Identity of this package.
 PACKAGE_NAME='cdsware'
 PACKAGE_TARNAME='cdsware'
-PACKAGE_VERSION='0.01-pre3'
-PACKAGE_STRING='cdsware 0.01-pre3'
+PACKAGE_VERSION='0.01-pre4'
+PACKAGE_STRING='cdsware 0.01-pre4'
 PACKAGE_BUGREPORT='cds.support@cern.ch'
 
 ac_prev=
@@ -545,7 +545,7 @@ if test "$ac_init_help" = "long"; then
   # Omit some internal or obsolete options to make the list less imposing.
   # This message is too long to be a string in the A/UX 3.1 sh.
   cat <<EOF
-\`configure' configures cdsware 0.01-pre3 to adapt to many kinds of systems.
+\`configure' configures cdsware 0.01-pre4 to adapt to many kinds of systems.
 
 Usage: $0 [OPTION]... [VAR=VALUE]...
 
@@ -607,7 +607,7 @@ fi
 
 if test -n "$ac_init_help"; then
   case $ac_init_help in
-     short | recursive ) echo "Configuration of cdsware 0.01-pre3:";;
+     short | recursive ) echo "Configuration of cdsware 0.01-pre4:";;
    esac
   cat <<\EOF
 
@@ -672,7 +672,7 @@ fi
 test -n "$ac_init_help" && exit 0
 if $ac_init_version; then
   cat <<\EOF
-cdsware configure 0.01-pre3
+cdsware configure 0.01-pre4
 generated by GNU Autoconf 2.52
 
 Copyright 1992, 1993, 1994, 1995, 1996, 1998, 1999, 2000, 2001
@@ -687,7 +687,7 @@ cat >&5 <<EOF
 This file contains any messages produced by compilers while
 running configure, to aid debugging if configure makes a mistake.
 
-It was created by cdsware $as_me 0.01-pre3, which was
+It was created by cdsware $as_me 0.01-pre4, which was
 generated by GNU Autoconf 2.52.  Invocation command line was
 
   $ $0 $@
@@ -1100,7 +1100,7 @@ fi
 
 PACKAGE=cdsware
 
-VERSION=0.01-pre3
+VERSION=0.01-pre4
 
 if test "`cd $srcdir && pwd`" != "`pwd`" && test -f $srcdir/config.status; then
   { { echo "$as_me:1106: error: source directory already configured; run \"make distclean\" there first" >&5
@@ -1629,7 +1629,7 @@ ac_config_commands="$ac_config_commands default-19"
 
 ac_config_commands="$ac_config_commands default-20"
 
-ac_config_files="$ac_config_files Makefile config/Makefile config/configbis.wml cgibin/Makefile dbutil/Makefile htdocs/Makefile htdocs/img/Makefile htdocs/submit/Makefile htdocs/personalize/Makefile htdocs/docs/Makefile htdocs/bibformat/Makefile htdocs/bibformat/core/Makefile htdocs/bibformat/common/Makefile htdocs/admin/Makefile htdocs/admin/howto/Makefile htdocs/admin/bibconvert/Makefile htdocs/admin/bibdata/Makefile htdocs/admin/bibformat/Makefile htdocs/admin/bibharvest/Makefile htdocs/admin/bibupload/Makefile htdocs/admin/bibwords/Makefile htdocs/admin/webaccess/Makefile htdocs/admin/websearch/Makefile htdocs/admin/websubmit/Makefile htdocs/admin/webperso/Makefile"
+ac_config_files="$ac_config_files Makefile config/Makefile config/configbis.wml cgibin/Makefile dbutil/Makefile htdocs/Makefile htdocs/img/Makefile htdocs/submit/Makefile htdocs/submit/errors/Makefile htdocs/personalize/Makefile htdocs/docs/Makefile htdocs/bibformat/Makefile htdocs/bibformat/core/Makefile htdocs/bibformat/common/Makefile htdocs/admin/Makefile htdocs/admin/howto/Makefile htdocs/admin/bibconvert/Makefile htdocs/admin/bibdata/Makefile htdocs/admin/bibformat/Makefile htdocs/admin/bibharvest/Makefile htdocs/admin/bibupload/Makefile htdocs/admin/bibwords/Makefile htdocs/admin/webaccess/Makefile htdocs/admin/websearch/Makefile htdocs/admin/websubmit/Makefile htdocs/admin/webperso/Makefile"
 cat >confcache <<\_ACEOF
 # This file is a shell script that caches the results of configure
 # tests run on this system so they can be shared between configure
@@ -1865,7 +1865,7 @@ EOF
 
 cat >>$CONFIG_STATUS <<EOF
 ac_cs_version="\\
-cdsware config.status 0.01-pre3
+cdsware config.status 0.01-pre4
 configured by $0, generated by GNU Autoconf 2.52,
   with options \\"`echo "$ac_configure_args" | sed 's/[\\""\`\$]/\\\\&/g'`\\"
 
@@ -1948,7 +1948,7 @@ cat >&5 << _ACEOF
 ## Running config.status.  ##
 ## ----------------------- ##
 
-This file was extended by $as_me (cdsware 0.01-pre3) 2.52, executed with
+This file was extended by $as_me (cdsware 0.01-pre4) 2.52, executed with
   CONFIG_FILES    = $CONFIG_FILES
   CONFIG_HEADERS  = $CONFIG_HEADERS
   CONFIG_LINKS    = $CONFIG_LINKS
@@ -1989,6 +1989,7 @@ do
   "htdocs/Makefile" ) CONFIG_FILES="$CONFIG_FILES htdocs/Makefile" ;;
   "htdocs/img/Makefile" ) CONFIG_FILES="$CONFIG_FILES htdocs/img/Makefile" ;;
   "htdocs/submit/Makefile" ) CONFIG_FILES="$CONFIG_FILES htdocs/submit/Makefile" ;;
+  "htdocs/submit/errors/Makefile" ) CONFIG_FILES="$CONFIG_FILES htdocs/submit/errors/Makefile" ;;
   "htdocs/personalize/Makefile" ) CONFIG_FILES="$CONFIG_FILES htdocs/personalize/Makefile" ;;
   "htdocs/docs/Makefile" ) CONFIG_FILES="$CONFIG_FILES htdocs/docs/Makefile" ;;
   "htdocs/bibformat/Makefile" ) CONFIG_FILES="$CONFIG_FILES htdocs/bibformat/Makefile" ;;
@@ -2026,7 +2027,7 @@ do
   "default-18" ) CONFIG_COMMANDS="$CONFIG_COMMANDS default-18" ;;
   "default-19" ) CONFIG_COMMANDS="$CONFIG_COMMANDS default-19" ;;
   "default-20" ) CONFIG_COMMANDS="$CONFIG_COMMANDS default-20" ;;
-  *) { { echo "$as_me:2029: error: invalid argument: $ac_config_target" >&5
+  *) { { echo "$as_me:2030: error: invalid argument: $ac_config_target" >&5
 echo "$as_me: error: invalid argument: $ac_config_target" >&2;}
    { (exit 1); exit 1; }; };;
   esac
@@ -2246,7 +2247,7 @@ done; }
   esac
 
   if test x"$ac_file" != x-; then
-    { echo "$as_me:2249: creating $ac_file" >&5
+    { echo "$as_me:2250: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
     rm -f "$ac_file"
   fi
@@ -2264,7 +2265,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:2267: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:2268: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -2277,7 +2278,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:2280: error: cannot find input file: $f" >&5
+           { { echo "$as_me:2281: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
