Added PHP standalone executable.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1,6 +1,6 @@
 #! /bin/sh
 # Guess values for system-dependent variables and create Makefiles.
-# Generated by Autoconf 2.52 for cdsware 0.01.
+# Generated by Autoconf 2.52 for cdsware 0.01pre1.
 #
 # Report bugs to <cds.support@cern.ch>.
 #
@@ -147,8 +147,8 @@ mandir='${prefix}/man'
 # Identity of this package.
 PACKAGE_NAME='cdsware'
 PACKAGE_TARNAME='cdsware'
-PACKAGE_VERSION='0.01'
-PACKAGE_STRING='cdsware 0.01'
+PACKAGE_VERSION='0.01pre1'
+PACKAGE_STRING='cdsware 0.01pre1'
 PACKAGE_BUGREPORT='cds.support@cern.ch'
 
 ac_prev=
@@ -545,7 +545,7 @@ if test "$ac_init_help" = "long"; then
   # Omit some internal or obsolete options to make the list less imposing.
   # This message is too long to be a string in the A/UX 3.1 sh.
   cat <<EOF
-\`configure' configures cdsware 0.01 to adapt to many kinds of systems.
+\`configure' configures cdsware 0.01pre1 to adapt to many kinds of systems.
 
 Usage: $0 [OPTION]... [VAR=VALUE]...
 
@@ -607,7 +607,7 @@ fi
 
 if test -n "$ac_init_help"; then
   case $ac_init_help in
-     short | recursive ) echo "Configuration of cdsware 0.01:";;
+     short | recursive ) echo "Configuration of cdsware 0.01pre1:";;
    esac
   cat <<\EOF
 
@@ -672,7 +672,7 @@ fi
 test -n "$ac_init_help" && exit 0
 if $ac_init_version; then
   cat <<\EOF
-cdsware configure 0.01
+cdsware configure 0.01pre1
 generated by GNU Autoconf 2.52
 
 Copyright 1992, 1993, 1994, 1995, 1996, 1998, 1999, 2000, 2001
@@ -687,7 +687,7 @@ cat >&5 <<EOF
 This file contains any messages produced by compilers while
 running configure, to aid debugging if configure makes a mistake.
 
-It was created by cdsware $as_me 0.01, which was
+It was created by cdsware $as_me 0.01pre1, which was
 generated by GNU Autoconf 2.52.  Invocation command line was
 
   $ $0 $@
@@ -1100,7 +1100,7 @@ fi
 
 PACKAGE=cdsware
 
-VERSION=0.01
+VERSION=0.01-pre1
 
 if test "`cd $srcdir && pwd`" != "`pwd`" && test -f $srcdir/config.status; then
   { { echo "$as_me:1106: error: source directory already configured; run \"make distclean\" there first" >&5
@@ -1354,9 +1354,56 @@ echo "$as_me: error:
    { (exit 1); exit 1; }; }
 fi
 
+# Extract the first word of "php", so it can be a program name with args.
+set dummy php; ac_word=$2
+echo "$as_me:1359: checking for $ac_word" >&5
+echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
+if test "${ac_cv_path_PHP+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  case $PHP in
+  [\\/]* | ?:[\\/]*)
+  ac_cv_path_PHP="$PHP" # Let the user override the test with a path.
+  ;;
+  *)
+  ac_save_IFS=$IFS; IFS=$ac_path_separator
+ac_dummy="$PATH"
+for ac_dir in $ac_dummy; do
+  IFS=$ac_save_IFS
+  test -z "$ac_dir" && ac_dir=.
+  if $as_executable_p "$ac_dir/$ac_word"; then
+   ac_cv_path_PHP="$ac_dir/$ac_word"
+   echo "$as_me:1376: found $ac_dir/$ac_word" >&5
+   break
+fi
+done
+
+  ;;
+esac
+fi
+PHP=$ac_cv_path_PHP
+
+if test -n "$PHP"; then
+  echo "$as_me:1387: result: $PHP" >&5
+echo "${ECHO_T}$PHP" >&6
+else
+  echo "$as_me:1390: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+
+if test -z "$PHP"; then
+   { { echo "$as_me:1395: error:
+   PHP standalone command-line executable (i.e. not compiled as Apache module!) is required too.
+   Available from <http://www.php.net/manual/en/install.commandline.php>." >&5
+echo "$as_me: error:
+   PHP standalone command-line executable (i.e. not compiled as Apache module!) is required too.
+   Available from <http://www.php.net/manual/en/install.commandline.php>." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+
 # Extract the first word of "perl", so it can be a program name with args.
 set dummy perl; ac_word=$2
-echo "$as_me:1359: checking for $ac_word" >&5
+echo "$as_me:1406: checking for $ac_word" >&5
 echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
 if test "${ac_cv_path_PERL+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
@@ -1373,7 +1420,7 @@ for ac_dir in $ac_dummy; do
   test -z "$ac_dir" && ac_dir=.
   if $as_executable_p "$ac_dir/$ac_word"; then
    ac_cv_path_PERL="$ac_dir/$ac_word"
-   echo "$as_me:1376: found $ac_dir/$ac_word" >&5
+   echo "$as_me:1423: found $ac_dir/$ac_word" >&5
    break
 fi
 done
@@ -1384,15 +1431,15 @@ fi
 PERL=$ac_cv_path_PERL
 
 if test -n "$PERL"; then
-  echo "$as_me:1387: result: $PERL" >&5
+  echo "$as_me:1434: result: $PERL" >&5
 echo "${ECHO_T}$PERL" >&6
 else
-  echo "$as_me:1390: result: no" >&5
+  echo "$as_me:1437: result: no" >&5
 echo "${ECHO_T}no" >&6
 fi
 
 if test -z "$PERL"; then
-   { { echo "$as_me:1395: error:
+   { { echo "$as_me:1442: error:
    Perl is required.  Available from <http://cpan.org/>." >&5
 echo "$as_me: error:
    Perl is required.  Available from <http://cpan.org/>." >&2;}
@@ -1401,7 +1448,7 @@ fi
 
 # Extract the first word of "python", so it can be a program name with args.
 set dummy python; ac_word=$2
-echo "$as_me:1404: checking for $ac_word" >&5
+echo "$as_me:1451: checking for $ac_word" >&5
 echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
 if test "${ac_cv_path_PYTHON+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
@@ -1418,7 +1465,7 @@ for ac_dir in $ac_dummy; do
   test -z "$ac_dir" && ac_dir=.
   if $as_executable_p "$ac_dir/$ac_word"; then
    ac_cv_path_PYTHON="$ac_dir/$ac_word"
-   echo "$as_me:1421: found $ac_dir/$ac_word" >&5
+   echo "$as_me:1468: found $ac_dir/$ac_word" >&5
    break
 fi
 done
@@ -1429,15 +1476,15 @@ fi
 PYTHON=$ac_cv_path_PYTHON
 
 if test -n "$PYTHON"; then
-  echo "$as_me:1432: result: $PYTHON" >&5
+  echo "$as_me:1479: result: $PYTHON" >&5
 echo "${ECHO_T}$PYTHON" >&6
 else
-  echo "$as_me:1435: result: no" >&5
+  echo "$as_me:1482: result: no" >&5
 echo "${ECHO_T}no" >&6
 fi
 
 if test -z "$PYTHON"; then
-   { { echo "$as_me:1440: error:
+   { { echo "$as_me:1487: error:
    Python is required.  Available from <http://python.org/>." >&5
 echo "$as_me: error:
    Python is required.  Available from <http://python.org/>." >&2;}
@@ -1450,7 +1497,7 @@ if test "${with_htdocsdir+set}" = set; then
   HTDOCSDIR=${withval}
 fi;
 if test -z "$HTDOCSDIR"; then
-   { { echo "$as_me:1453: error:
+   { { echo "$as_me:1500: error:
    You have not used \"--with-htdocsdir\" argument that defines the installation directory for HTML documents.
    Example: \"--with-htdocsdir=/soft/httpd/host/cdsdev/htdocs/MPI/\"." >&5
 echo "$as_me: error:
@@ -1465,7 +1512,7 @@ if test "${with_cgibindir+set}" = set; then
   CGIBINDIR=${withval}
 fi;
 if test -z "$CGIBINDIR"; then
-   { { echo "$as_me:1468: error:
+   { { echo "$as_me:1515: error:
    You have not used \"--with-cgibindir\" argument that defines the installation directory for CGI scripts.
    Example: \"--with-cgibindir=/soft/httpd/host/cdsdev/cgi-bin/MPI/\"." >&5
 echo "$as_me: error:
@@ -1480,7 +1527,7 @@ if test "${with_dbutildir+set}" = set; then
   DBUTILDIR=${withval}
 fi;
 if test -z "$DBUTILDIR"; then
-   { { echo "$as_me:1483: error:
+   { { echo "$as_me:1530: error:
    You have not used \"--with-dbutil\" argument that defines the installation directory for DB utilitites.
    Example: \"--with-dbutildir=/usr/local/bin/MPI/\"." >&5
 echo "$as_me: error:
@@ -1495,7 +1542,7 @@ if test "${with_htdocsurl+set}" = set; then
   HTDOCSURL=${withval}
 fi;
 if test -z "$HTDOCSURL"; then
-   { { echo "$as_me:1498: error:
+   { { echo "$as_me:1545: error:
    You have not used \"--with-htdocsurl\" argument that defines the URL where the HTML documents will be reached.
    Example: \"--with-htdocsurl=http://cdsdev.cern.ch/MPI/\"." >&5
 echo "$as_me: error:
@@ -1510,7 +1557,7 @@ if test "${with_cgibinurl+set}" = set; then
   CGIBINURL=${withval}
 fi;
 if test -z "$CGIBINURL"; then
-   { { echo "$as_me:1513: error:
+   { { echo "$as_me:1560: error:
    You have not used \"--with-cgibinurl\" argument that defines the URL where the HTML documents will be reached.
    Example: \"--with-cgibinurl=http://cdsdev.cern.ch/cgi-bin/MPI/\"." >&5
 echo "$as_me: error:
@@ -1525,7 +1572,7 @@ if test "${with_dbhost+set}" = set; then
   DBHOST=${withval}
 fi;
 if test -z "$DBHOST"; then
-   { { echo "$as_me:1528: error:
+   { { echo "$as_me:1575: error:
    You have not used \"--with-dbhost\" argument that defines which DB server to use.
    Example: \"--with-dbhost=cdsdb.cern.ch\"." >&5
 echo "$as_me: error:
@@ -1540,7 +1587,7 @@ if test "${with_dbname+set}" = set; then
   DBNAME=${withval}
 fi;
 if test -z "$DBNAME"; then
-   { { echo "$as_me:1543: error:
+   { { echo "$as_me:1590: error:
    You have not used \"--with-dbname\" argument that defines CDSware database name.
    Example: \"--with-dbname=cdsware\"." >&5
 echo "$as_me: error:
@@ -1555,7 +1602,7 @@ if test "${with_dbuser+set}" = set; then
   DBUSER=${withval}
 fi;
 if test -z "$DBUSER"; then
-   { { echo "$as_me:1558: error:
+   { { echo "$as_me:1605: error:
    You have not used \"--with-dbuser\" argument that defines DB user name.
    Example: \"--with-dbuser=cdsware\"." >&5
 echo "$as_me: error:
@@ -1570,7 +1617,7 @@ if test "${with_dbpass+set}" = set; then
   DBPASS=${withval}
 fi;
 if test -z "$DBPASS"; then
-   { { echo "$as_me:1573: error:
+   { { echo "$as_me:1620: error:
    You have not used \"--with-dbpass\" argument that defines DB user password.
    Example: \"--with-dbpass=myp1ss\"." >&5
 echo "$as_me: error:
@@ -1729,7 +1776,7 @@ rm -f confdef2opt.sed
 : ${CONFIG_STATUS=./config.status}
 ac_clean_files_save=$ac_clean_files
 ac_clean_files="$ac_clean_files $CONFIG_STATUS"
-{ echo "$as_me:1732: creating $CONFIG_STATUS" >&5
+{ echo "$as_me:1779: creating $CONFIG_STATUS" >&5
 echo "$as_me: creating $CONFIG_STATUS" >&6;}
 cat >$CONFIG_STATUS <<_ACEOF
 #! $SHELL
@@ -1855,7 +1902,7 @@ EOF
 
 cat >>$CONFIG_STATUS <<EOF
 ac_cs_version="\\
-cdsware config.status 0.01
+cdsware config.status 0.01pre1
 configured by $0, generated by GNU Autoconf 2.52,
   with options \\"`echo "$ac_configure_args" | sed 's/[\\""\`\$]/\\\\&/g'`\\"
 
@@ -1900,7 +1947,7 @@ cat >>$CONFIG_STATUS <<\EOF
     echo "$ac_cs_version"; exit 0 ;;
   --he | --h)
     # Conflict between --help and --header
-    { { echo "$as_me:1903: error: ambiguous option: $1
+    { { echo "$as_me:1950: error: ambiguous option: $1
 Try \`$0 --help' for more information." >&5
 echo "$as_me: error: ambiguous option: $1
 Try \`$0 --help' for more information." >&2;}
@@ -1919,7 +1966,7 @@ Try \`$0 --help' for more information." >&2;}
     ac_need_defaults=false;;
 
   # This is an error.
-  -*) { { echo "$as_me:1922: error: unrecognized option: $1
+  -*) { { echo "$as_me:1969: error: unrecognized option: $1
 Try \`$0 --help' for more information." >&5
 echo "$as_me: error: unrecognized option: $1
 Try \`$0 --help' for more information." >&2;}
@@ -1938,7 +1985,7 @@ cat >&5 << _ACEOF
 ## Running config.status.  ##
 ## ----------------------- ##
 
-This file was extended by $as_me (cdsware 0.01) 2.52, executed with
+This file was extended by $as_me (cdsware 0.01pre1) 2.52, executed with
   CONFIG_FILES    = $CONFIG_FILES
   CONFIG_HEADERS  = $CONFIG_HEADERS
   CONFIG_LINKS    = $CONFIG_LINKS
@@ -2002,7 +2049,7 @@ do
   "default-18" ) CONFIG_COMMANDS="$CONFIG_COMMANDS default-18" ;;
   "default-19" ) CONFIG_COMMANDS="$CONFIG_COMMANDS default-19" ;;
   "default-20" ) CONFIG_COMMANDS="$CONFIG_COMMANDS default-20" ;;
-  *) { { echo "$as_me:2005: error: invalid argument: $ac_config_target" >&5
+  *) { { echo "$as_me:2052: error: invalid argument: $ac_config_target" >&5
 echo "$as_me: error: invalid argument: $ac_config_target" >&2;}
    { (exit 1); exit 1; }; };;
   esac
@@ -2096,6 +2143,7 @@ s,@MAKEINFO@,$MAKEINFO,;t t
 s,@SET_MAKE@,$SET_MAKE,;t t
 s,@WML@,$WML,;t t
 s,@MYSQL@,$MYSQL,;t t
+s,@PHP@,$PHP,;t t
 s,@PERL@,$PERL,;t t
 s,@PYTHON@,$PYTHON,;t t
 s,@HTDOCSDIR@,$HTDOCSDIR,;t t
@@ -2221,7 +2269,7 @@ done; }
   esac
 
   if test x"$ac_file" != x-; then
-    { echo "$as_me:2224: creating $ac_file" >&5
+    { echo "$as_me:2272: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
     rm -f "$ac_file"
   fi
@@ -2239,7 +2287,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:2242: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:2290: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -2252,7 +2300,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:2255: error: cannot find input file: $f" >&5
+           { { echo "$as_me:2303: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
@@ -2291,26 +2339,26 @@ for ac_file in : $CONFIG_COMMANDS; do test "x$ac_file" = x: && continue
   ac_source=`echo "$ac_file" | sed 's,[^:]*:,,'`
 
   case $ac_dest in
-    default-1 ) echo "*******************************************************************************" ;;
-    default-2 ) echo "Good, the CERN Document Server Software (CDSware) is now ready for installation!" ;;
-    default-3 ) echo "You have entered the following parameters:" ;;
-    default-4 ) echo "  * HTML documents install directory: $X1" ;;
-    default-5 ) echo "  * CGI scripts install directory: $X2" ;;
-    default-6 ) echo "  * DB utilities install directory: $X3" ;;
-    default-7 ) echo "  * HTML documents home URL: $X4" ;;
-    default-8 ) echo "  * CGI scripts home URL: $X5" ;;
-    default-9 ) echo "  * DB server: $X6" ;;
-    default-10 ) echo "  * DB table name: $X7" ;;
-    default-11 ) echo "  * DB username: $X8" ;;
-    default-12 ) echo "  * DB password: $X9" ;;
-    default-13 ) echo "Here are the steps to continue the building process:" ;;
-    default-14 ) echo "  - Firstly, customize the self-explanatory config file './config/config.wml'." ;;
-    default-15 ) echo "  - Secondly, type 'make' to build your customized CDSware installation." ;;
-    default-16 ) echo "  - Thirdly, type 'make create-tables' if you have not created CDSware tables yet." ;;
-    default-17 ) echo "  - Finally, type 'make install' to install the system." ;;
-    default-18 ) echo "Good luck, and thanks for choosing the CERN Document Server Software." ;;
-    default-19 ) echo "             -- CDSware Development Group <cds.support@cern.ch>" ;;
-    default-20 ) echo "*******************************************************************************" ;;
+    default-1 ) echo "****************************************************************************************" ;;
+    default-2 ) echo "** Good, the CERN Document Server Software (CDSware) is now ready for installation!   **" ;;
+    default-3 ) echo "** You have entered the following parameters:                                         **" ;;
+    default-4 ) echo "**   - HTML documents install directory: $X1" ;;
+    default-5 ) echo "**   - CGI scripts install directory: $X2" ;;
+    default-6 ) echo "**   - DB utilities install directory: $X3" ;;
+    default-7 ) echo "**   - HTML documents home URL: $X4" ;;
+    default-8 ) echo "**   - CGI scripts home URL: $X5" ;;
+    default-9 ) echo "**   - DB server: $X6" ;;
+    default-10 ) echo "**   - DB table name: $X7" ;;
+    default-11 ) echo "**   - DB username: $X8" ;;
+    default-12 ) echo "**   - DB password: $X9" ;;
+    default-13 ) echo "** Here are the steps to continue the building process:                               **" ;;
+    default-14 ) echo "**   - Firstly, customize the self-explanatory config file './config/config.wml'.     **" ;;
+    default-15 ) echo "**   - Secondly, type 'make' to build your customized CDSware installation.           **" ;;
+    default-16 ) echo "**   - Thirdly, type 'make create-tables' if you have not created CDSware tables yet. **" ;;
+    default-17 ) echo "**   - Finally, type 'make install' to install the system.                            **" ;;
+    default-18 ) echo "** Good luck, and thanks for choosing the CERN Document Server Software.              **" ;;
+    default-19 ) echo "**              -- CDS Development Group <cds.support@cern.ch>                        **" ;;
+    default-20 ) echo "****************************************************************************************" ;;
   esac
 done
 EOF
